title: Satya Vakiti # your name (or website title) here
logo: "SatyaVakiti.github.io/images/1611540058733.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mechanical Product Manager  
  <br><br>
  Expert in data analytics
  <br><br>
  <a href="https://www.linkedin.com/in/satyavakiti/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
